version: '3.2'
services:  
  Kibana:
    image: kibana:7.8.0

    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://70.37.52.245:9700
      ELASTICSEARCH_HOSTS: http://70.37.52.245:9700
  
  LogstasCSV:
    image: logstash:7.8.0

    ports:
      - 5450:5450

    volumes:
      - ./logstash/data/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/jvm.options:/usr/share/logstash/config/jvm.options
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /home/MemoRT3/ELK3/logstash/data/olympic.csv:/data/olympic.csv:ro
