
#filebeat.yml

filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /data/apache_logs.log

setup.template.settings:
  index.number_of_shards: 1


output.logstash:
  hosts: ["104.214.56.20:9704"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
