#**************************************************************************
#filebeat.yml
#**************************************************************************

filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /home/MemoRT2/ELK2/filebeat2/logstash-tutorial.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1


output.logstash:
  hosts: ["104.214.56.20:9704"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
