metricbeat.modules:

- module: system
  metricsets: ["cpu", "load", "filesystem", "fsstat", "memory", "network", "process", "core", "diskio", "socket"]
  period: 10s
  enabled: true
  processes: ['.*']
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

output.logstash:
  hosts: ["104.214.56.20:9706"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
